"use server";

import { headers } from "next/headers";

import { clientIp } from "@/server/core/request";
import { createBooking } from "@/server/services/booking";

import { loadAvailability, type DaySlots } from "./booking";

/**
 * The booking form's write path.
 *
 * A Server Action rather than an API route so the form works without
 * JavaScript-authored fetch plumbing, and so the same function is the only way
 * in. Everything security-relevant lives one layer down in
 * `server/services/booking.ts`: rate limiting, idempotency, server-side price
 * resolution and the slot re-check. This file only translates form data.
 *
 * 🔴 Notice what is NOT accepted from the browser: no price amount, no branch,
 * no customer id, no total. The client names a duration by its immutable id and
 * nothing else about money.
 */

/**
 * 🔴 Carries an error CODE, never a message.
 *
 * `AppError.message` is written for logs and developers, and on this path it is
 * assembled in `server/rekaz/client.ts` from up to 300 characters of the raw
 * upstream response body, Rekaz's `traceId`, and our own internal method and
 * path. `toPublicError` exists to strip exactly that, but it is wired into
 * `route()`, which a Server Action never passes through, and Next redacts
 * THROWN errors rather than RETURNED action values. So a returned message
 * serialises to the browser verbatim.
 *
 * Returning the code instead means the browser sees a fixed vocabulary and the
 * page renders its own copy, in the reader's own language. That second part is
 * not a nicety: the service's strings are English, and this form ships on
 * the Arabic booking pages.
 */
export type BookingFormState =
  | { status: "idle" }
  | { status: "error"; code: string; field?: string }
  | { status: "ready"; paymentLink: string };

export async function submitBooking(
  _previous: BookingFormState,
  formData: FormData
): Promise<BookingFormState> {
  const requestHeaders = await headers();

  const customFields: Record<string, string> = {};
  for (const [key, value] of formData.entries()) {
    // Custom fields arrive prefixed so they cannot collide with our own inputs
    // and so a crafted form cannot inject arbitrary keys into the Rekaz payload.
    if (key.startsWith("cf:") && typeof value === "string" && value.trim()) {
      customFields[key.slice(3)] = value.trim();
    }
  }

  const result = await createBooking({
    space: String(formData.get("space") ?? ""),
    priceImmutableId: String(formData.get("priceImmutableId") ?? ""),
    slotFrom: str(formData.get("slotFrom")),
    slotTo: str(formData.get("slotTo")),
    startAt: str(formData.get("startAt")),
    customFields,
    customer: {
      name: String(formData.get("name") ?? ""),
      mobile: String(formData.get("mobile") ?? ""),
      email: str(formData.get("email")),
    },
    // Generated by the client per booking attempt and resubmitted unchanged on
    // retry. That is what makes a double-tap return the first payment link
    // instead of creating a second reservation.
    idempotencyKey: String(formData.get("idempotencyKey") ?? ""),
    ip: clientIp(requestHeaders),
  });

  if (!result.ok) {
    return {
      status: "error",
      code: result.error.code,
      field: result.error.fields ? Object.keys(result.error.fields)[0] : undefined,
    };
  }

  // The redirect itself happens client-side. Returning the link rather than
  // calling `redirect()` here keeps the action's result inspectable and lets the
  // form show a spinner during the hand-off instead of a blank frame.
  return { status: "ready", paymentLink: result.value.paymentLink };
}

/** Availability for a chosen duration, fetched when the picker changes. */
export async function fetchAvailability(
  spaceSlug: string,
  priceImmutableId: string
): Promise<DaySlots[] | null> {
  return loadAvailability(spaceSlug, priceImmutableId);
}

function str(value: FormDataEntryValue | null): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed === "" ? undefined : trimmed;
}
