"use server";

import { headers } from "next/headers";

import { clientIp } from "@/server/core/request";
import { createBooking } from "@/server/services/booking";

import { loadAvailability, type Availability } from "./booking";

/**
 * The booking form's write path.
 *
 * A Server Action rather than an API route so the form works without
 * JavaScript-authored fetch plumbing, and so the same function is the only way
 * in. Everything security-relevant lives one layer down in
 * `server/services/booking.ts`: rate limiting, idempotency, server-side price
 * resolution and the slot re-check. This file only translates form data.
 *
 * 🔴 Notice what is NOT accepted from the browser: no price amount, no branch,
 * no customer id, no total. The client names a duration by its immutable id and
 * nothing else about money.
 */

/**
 * 🔴 Carries an error CODE, never a message.
 *
 * `AppError.message` is written for logs and developers, and on this path it is
 * assembled in `server/rekaz/client.ts` from up to 300 characters of the raw
 * upstream response body, Rekaz's `traceId`, and our own internal method and
 * path. `toPublicError` exists to strip exactly that, but it is wired into
 * `route()`, which a Server Action never passes through, and Next redacts
 * THROWN errors rather than RETURNED action values. So a returned message
 * serialises to the browser verbatim.
 *
 * Returning the code instead means the browser sees a fixed vocabulary and the
 * page renders its own copy, in the reader's own language. That second part is
 * not a nicety: the service's strings are English, and this form ships on
 * the Arabic booking pages.
 */
export type BookingFormState =
  | { status: "idle" }
  | {
      status: "error";
      code: string;
      field?: string;
      /**
       * Rekaz's own booking reference, present ONLY when a write we could not
       * confirm turned out to have succeeded. It is the single thing that lets
       * the customer and MAZJ resolve that booking by hand, since Rekaz exposes
       * no way to recover a payment link for an existing booking.
       */
      reference?: string;
    }
  | { status: "ready"; paymentLink: string };

/**
 * The booking outcomes that travel as `conflict` but must not read as "that
 * slot just went".
 *
 * A table rather than a chain of ternaries so the code names are greppable
 * against the `Booking.error.*` keys in `messages/{en,ar}.json`. Typed with an
 * explicit `undefined` in the value so the `??` fallback below is honest under
 * either setting of `noUncheckedIndexedAccess`.
 *
 * 🔴 NOT exported. This file is `"use server"`, so every export becomes a
 * publicly callable Server Action.
 */
const BOOKING_STATE_CODES: Record<string, string | undefined> = {
  in_flight: "booking_in_flight",
  unconfirmed: "booking_unconfirmed",
};

export async function submitBooking(
  _previous: BookingFormState,
  formData: FormData
): Promise<BookingFormState> {
  const requestHeaders = await headers();

  const customFields: Record<string, string> = {};
  for (const [key, value] of formData.entries()) {
    // Custom fields arrive prefixed so they cannot collide with our own inputs
    // and so a crafted form cannot inject arbitrary keys into the Rekaz payload.
    if (key.startsWith("cf:") && typeof value === "string" && value.trim()) {
      customFields[key.slice(3)] = value.trim();
    }
  }

  const result = await createBooking({
    space: String(formData.get("space") ?? ""),
    priceImmutableId: String(formData.get("priceImmutableId") ?? ""),
    slotFrom: str(formData.get("slotFrom")),
    slotTo: str(formData.get("slotTo")),
    startAt: str(formData.get("startAt")),
    customFields,
    customer: {
      name: String(formData.get("name") ?? ""),
      mobile: String(formData.get("mobile") ?? ""),
      email: str(formData.get("email")),
    },
    // Generated by the client per booking attempt and resubmitted unchanged on
    // retry. That is what makes a double-tap return the first payment link
    // instead of creating a second reservation.
    idempotencyKey: String(formData.get("idempotencyKey") ?? ""),
    ip: clientIp(requestHeaders),
  });

  if (!result.ok) {
    // A confirmed-but-unpayable booking carries a reference and needs its own
    // copy: "that time was just taken" and "you ARE booked, ring us" are both
    // `conflict`, and telling a booked customer to pick another slot would be
    // the worst possible advice.
    const fields = result.error.fields;
    const reference = fields?.reference;

    // 🔴 The same trap, one step less obvious. Four MORE outcomes arrive as
    // `conflict` and not one of them is "that slot just went": a first attempt
    // still in flight, a write we dispatched and could not confirm, a stored
    // result we could not read back, and a replay of a key closed as
    // indeterminate. All of them used to render `error.conflict`, i.e. "That
    // time was just taken. Please choose another.", which invites a customer
    // whose booking may ALREADY EXIST to buy the room a second time. On the open
    // desk and the private office, which have no time slot at all, it is not
    // even a sentence about anything on their screen.
    //
    // The service marks them in `fields.booking`; this is where that becomes a
    // code the page has copy for.
    const stateCode = BOOKING_STATE_CODES[fields?.booking ?? ""];

    return {
      status: "error",
      code: reference ? "booking_exists" : (stateCode ?? result.error.code),
      // Only a real validation failure names a form control. `reference` and
      // `booking` ride in the same bag, and reporting either as "the field that
      // was wrong" would point the form at an input that does not exist.
      field:
        result.error.code === "validation_failed" && fields
          ? Object.keys(fields)[0]
          : undefined,
      ...(reference ? { reference } : {}),
    };
  }

  // The redirect itself happens client-side. Returning the link rather than
  // calling `redirect()` here keeps the action's result inspectable and lets the
  // form show a spinner during the hand-off instead of a blank frame.
  return { status: "ready", paymentLink: result.value.paymentLink };
}

/** Availability for a chosen duration, fetched when the picker changes. */
export async function fetchAvailability(
  spaceSlug: string,
  priceImmutableId: string
): Promise<Availability> {
  return loadAvailability(spaceSlug, priceImmutableId);
}

function str(value: FormDataEntryValue | null): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed === "" ? undefined : trimmed;
}
