"use server";

import { headers } from "next/headers";

import { clientIp } from "@/server/core/request";
import { submitStartupApplication } from "@/server/services/startup-application";

/**
 * The startup application's write path.
 *
 * A Server Action rather than an API route, matching the booking form: one
 * function, no fetch plumbing, and no second way in. Everything
 * security-relevant lives one layer down in
 * `server/services/startup-application.ts`: two rate-limit dimensions,
 * idempotency, normalisation and the duplicate-application rule. This file
 * translates `FormData` and nothing else.
 *
 * 🔴 The `_lib` folder is a SANCTIONED ESLint boundary crossing, and that makes
 * it a privileged location: anything in here can reach the Supabase secret key.
 * Keep it to translation, and keep the deciding downstairs.
 */

/**
 * 🔴 Carries an error CODE, never a message.
 *
 * `route()` and `toPublicError` are wired into `app/api/**` handlers only, and
 * Next redacts THROWN errors rather than RETURNED action values, so a returned
 * `AppError.message` serialises to the browser verbatim. That is not
 * theoretical here: this path's messages are assembled from database errors and
 * provider responses. The booking form shipped exactly that leak once, printing
 * 300 characters of upstream detail, a trace id and an internal path onto a
 * public page, in Arabic, on the English site.
 *
 * The browser gets a fixed vocabulary and the page renders its own copy from
 * `messages/*.json`, which is also the only way an Arabic visitor sees an
 * Arabic error: everything the service says is English.
 */
export type ApplicationFormState =
  | { status: "idle" }
  | { status: "error"; code: string; field?: string }
  | { status: "sent"; reference: string };

export async function submitApplication(
  _previous: ApplicationFormState,
  formData: FormData
): Promise<ApplicationFormState> {
  const requestHeaders = await headers();

  const result = await submitStartupApplication({
    founderName: str(formData.get("founderName")),
    startupName: str(formData.get("startupName")),
    email: str(formData.get("email")),
    mobile: str(formData.get("mobile")),
    pitch: str(formData.get("pitch")),
    stage: str(formData.get("stage")),
    teamSize: str(formData.get("teamSize")),
    space: str(formData.get("space")),
    // ⚠️ Read from a hidden input rather than inferred here. A Server Action
    // has no route context, so `headers()` cannot tell us which locale the
    // visitor was reading, and getting this wrong means an Arabic founder gets
    // an English approval. The service narrows it to `en` | `ar` regardless of
    // what is posted, so a crafted value cannot write anything else.
    locale: str(formData.get("locale")),
    // Generated by the client per mounted form and resubmitted unchanged on a
    // retry, which is what makes a double tap file ONE application.
    idempotencyKey: str(formData.get("idempotencyKey")),
    ip: clientIp(requestHeaders),
  });

  if (!result.ok) {
    return {
      status: "error",
      code: result.error.code,
      // The first field the service objected to, so the form can point at it.
      // `conflict` also carries one (`email`), which is how the "you already
      // applied" case highlights the right input instead of shouting generally.
      field: result.error.fields
        ? Object.keys(result.error.fields)[0]
        : undefined,
    };
  }

  return { status: "sent", reference: result.value.reference };
}

function str(value: FormDataEntryValue | null): string {
  return typeof value === "string" ? value : "";
}
