-- MAZJ's event archive, 2022 to 2025: 41 events.
--
-- GENERATED by scripts/generate-events-archive-migration.py from the
-- `EventsPage.archive` arrays that used to live in messages/en.json and
-- messages/ar.json. Those arrays are deleted in the same change, because two
-- sources of truth for one list is a guarantee that somebody eventually edits
-- the wrong one.
--
-- Every row is historical, so every `ends_at` is already in the past and they
-- land in the archive by the same rule that will move a future event there.
-- There is no special case for "old" anywhere in the application.
--
-- 🔴 `date_precision` is doing real work here. Four of these record only a
-- month, and NONE records a time. The timestamps below carry anchor hours so
-- the column can be sorted; the formatter never renders them.
--
-- `summary_*` holds what the source called `h`: the card's second line, which
-- is a person on some rows and a descriptor on others. It was NOT split into a
-- host field, because that split would have been a guess, and a guess written
-- into a database is indistinguishable afterwards from a recorded fact.

insert into public.events
  (slug, status, title_en, title_ar, summary_en, summary_ar,
   starts_at, ends_at, date_precision, series, edition)
values
  ('digital-creativity-in-architectural-rendering', 'published', 'Digital Creativity in Architectural Rendering', 'الإبداع الرقمي في الإظهار المعماري', 'Asma Habib', 'أسماء حبيب', timestamptz '2025-02-01 06:00:00+00', timestamptz '2025-02-01 18:00:00+00', 'day', null, null),
  ('coffee-sketch-v9', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2025-01-25 06:00:00+00', timestamptz '2025-01-25 18:00:00+00', 'day', 'coffeeSketch', 'V9'),
  ('the-brand-factory-v3', 'published', 'The Brand Factory', 'مصنع العلامات', 'Osamah Khalil', 'أسامة خليل', timestamptz '2025-01-18 06:00:00+00', timestamptz '2025-01-18 18:00:00+00', 'day', 'brandFactory', 'V3'),
  ('an-evening-with-muhannad-al-malki', 'published', 'An evening with Muhannad Al-Malki', 'لقاء مع المهند المالكي', 'AIA Middle East award winner', 'الحائز على جائزة AIA الشرق الأوسط', timestamptz '2024-12-18 06:00:00+00', timestamptz '2024-12-18 18:00:00+00', 'day', null, null),
  ('coffee-sketch-v8', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2024-12-14 06:00:00+00', timestamptz '2024-12-14 18:00:00+00', 'day', 'coffeeSketch', 'V8'),
  ('the-brand-factory-v2', 'published', 'The Brand Factory', 'مصنع العلامات', 'a one-day design sprint', 'سباق تصميم ليوم واحد', timestamptz '2024-11-16 06:00:00+00', timestamptz '2024-11-16 18:00:00+00', 'day', 'brandFactory', 'V2'),
  ('an-evening-with-ahlam-al-furaihi', 'published', 'An evening with Ahlam Al-Furaihi', 'لقاء مع المهندسة أحلام الفريحي', 'architecture and practice', 'عن العمارة والممارسة', timestamptz '2024-02-15 06:00:00+00', timestamptz '2024-02-15 18:00:00+00', 'month', null, null),
  ('stillness-learning-and-momentum', 'published', 'Stillness, learning and momentum', 'هدوء وتعلّم وتحفيز', 'a guided session', 'جلسة موجّهة', timestamptz '2024-02-06 06:00:00+00', timestamptz '2024-02-06 18:00:00+00', 'day', null, null),
  ('the-brand-factory-v1', 'published', 'The Brand Factory', 'مصنع العلامات', 'a one-day design sprint', 'سباق تصميم ليوم واحد', timestamptz '2024-02-03 06:00:00+00', timestamptz '2024-02-03 18:00:00+00', 'day', 'brandFactory', 'V1'),
  ('the-power-of-design', 'published', 'The power of design', 'قوة التصميم', 'an art session', 'لقاء فني', timestamptz '2024-01-30 06:00:00+00', timestamptz '2024-01-30 18:00:00+00', 'day', null, null),
  ('urban-sketching', 'published', 'Urban Sketching', 'الرسم الحضري', 'drawing the city as it is', 'رسم المدينة كما هي', timestamptz '2024-01-27 06:00:00+00', timestamptz '2024-01-27 18:00:00+00', 'day', null, null),
  ('between-the-frames', 'published', 'Between the Frames', 'بين الإطارات', 'Mada Cultural Club', 'نادي مدى الثقافي', timestamptz '2023-12-05 06:00:00+00', timestamptz '2023-12-05 18:00:00+00', 'day', null, null),
  ('loqma-w-fayda-zahra-al-hussain-v6', 'published', 'Loqma w Fayda: Zahra Al-Hussain', 'لقمة وفايدة: زهراء الحسين', 'on managing what you build', 'عن إدارة ما تبنيه', timestamptz '2023-10-24 06:00:00+00', timestamptz '2023-10-24 18:00:00+00', 'day', 'loqmaFayda', 'V6'),
  ('rad-entrepreneurship-forum-open-session', 'published', 'RAD Entrepreneurship Forum: open session', 'اللقاء التعريفي لملتقى راد', 'Asharqia Chamber', 'غرفة الشرقية', timestamptz '2023-10-18 06:00:00+00', timestamptz '2023-10-18 18:00:00+00', 'day', null, null),
  ('arabic-calligraphy', 'published', 'Arabic Calligraphy', 'الخط العربي', 'a hands-on introduction', 'مدخل عملي', timestamptz '2023-10-17 06:00:00+00', timestamptz '2023-10-17 18:00:00+00', 'day', null, null),
  ('coffee-sketch-v7', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-09-30 06:00:00+00', timestamptz '2023-09-30 18:00:00+00', 'day', 'coffeeSketch', 'V7'),
  ('women-who-design-v4', 'published', 'Women Who Design', 'نساء يصمّمن', 'with Lamia of Vena', 'مع لمياء | ڤينا', timestamptz '2023-09-26 06:00:00+00', timestamptz '2023-09-26 18:00:00+00', 'day', 'womenDesign', 'V4'),
  ('loqma-w-fayda-khalid-al-musaad-v5', 'published', 'Loqma w Fayda: Khalid Al-Musaad', 'لقمة وفايدة: خالد المساعد', 'founder of Karkam', 'مؤسس كركم', timestamptz '2023-09-19 06:00:00+00', timestamptz '2023-09-19 18:00:00+00', 'day', 'loqmaFayda', 'V5'),
  ('documentary-night', 'published', 'Documentary night', 'ليلة الفيلم الوثائقي', 'a screening and a conversation', 'عرض وحوار', timestamptz '2023-09-04 06:00:00+00', timestamptz '2023-09-04 18:00:00+00', 'day', null, null),
  ('loqma-w-fayda-manal-ambon-v4', 'published', 'Loqma w Fayda: Manal Ambon', 'لقمة وفايدة: منال أمبون', 'on training and practice', 'عن التدريب والممارسة', timestamptz '2023-08-30 06:00:00+00', timestamptz '2023-08-30 18:00:00+00', 'day', 'loqmaFayda', 'V4'),
  ('coffee-sketch-v6', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-08-26 06:00:00+00', timestamptz '2023-08-26 18:00:00+00', 'day', 'coffeeSketch', 'V6'),
  ('design-through-the-philosophy-of-play', 'published', 'Design through the philosophy of play', 'التصميم بفلسفة اللعب', 'a workshop', 'ورشة عمل', timestamptz '2023-08-23 06:00:00+00', timestamptz '2023-08-23 18:00:00+00', 'day', null, null),
  ('women-who-design-v3', 'published', 'Women Who Design', 'نساء يصمّمن', 'with Alia Abdal', 'مع علياء عبدال', timestamptz '2023-08-09 06:00:00+00', timestamptz '2023-08-09 18:00:00+00', 'day', 'womenDesign', 'V3'),
  ('loqma-w-fayda-razan-al-jishi-v3', 'published', 'Loqma w Fayda: Razan Al-Jishi', 'لقمة وفايدة: رزان الجشي', 'coaching and the inner work', 'عن التدريب والعمل الداخلي', timestamptz '2023-07-25 06:00:00+00', timestamptz '2023-07-25 18:00:00+00', 'day', 'loqmaFayda', 'V3'),
  ('coffee-sketch-v5', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-07-22 06:00:00+00', timestamptz '2023-07-22 18:00:00+00', 'day', 'coffeeSketch', 'V5'),
  ('fus-ha', 'published', 'Fus-ha', 'فسحة', 'MAZJ with Studio Acumen', 'مزج مع ستوديو أكيومن', timestamptz '2023-07-18 06:00:00+00', timestamptz '2023-07-18 18:00:00+00', 'day', null, null),
  ('women-who-design-v2', 'published', 'Women Who Design', 'نساء يصمّمن', 'a founder''s evening', 'أمسية مؤسِّسة', timestamptz '2023-07-12 06:00:00+00', timestamptz '2023-07-12 18:00:00+00', 'day', 'womenDesign', 'V2'),
  ('women-who-design-v1', 'published', 'Women Who Design', 'نساء يصمّمن', 'the series opens', 'انطلاق السلسلة', timestamptz '2023-06-20 06:00:00+00', timestamptz '2023-06-20 18:00:00+00', 'day', 'womenDesign', 'V1'),
  ('coffee-sketch-v4', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-06-17 06:00:00+00', timestamptz '2023-06-17 18:00:00+00', 'day', 'coffeeSketch', 'V4'),
  ('loqma-w-fayda-dana-al-salah-v2', 'published', 'Loqma w Fayda: Dana Al Salah', 'لقمة وفايدة: دانة آل صلاح', 'founder of Ab', 'مؤسِّسة "أب"', timestamptz '2023-06-13 06:00:00+00', timestamptz '2023-06-13 18:00:00+00', 'day', 'loqmaFayda', 'V2'),
  ('art-direction', 'published', 'Art Direction', 'الإخراج الفني', 'the craft and its methods', 'الحرفة وأساليبها', timestamptz '2023-06-12 06:00:00+00', timestamptz '2023-06-12 18:00:00+00', 'day', null, null),
  ('coffee-sketch-v3', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-05-20 06:00:00+00', timestamptz '2023-05-20 18:00:00+00', 'day', 'coffeeSketch', 'V3'),
  ('botanical-ornament', 'published', 'Botanical ornament', 'الزخرفة النباتية', 'with a Ramadan touch', 'بلمسة رمضانية', timestamptz '2023-04-09 06:00:00+00', timestamptz '2023-04-09 18:00:00+00', 'day', null, null),
  ('creative-thinking', 'published', 'Creative thinking', 'التفكير الإبداعي', 'for architects and designers', 'للمعماريين والمصمِّمين', timestamptz '2023-03-15 06:00:00+00', timestamptz '2023-03-15 18:00:00+00', 'month', null, null),
  ('coffee-sketch-v2', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-03-11 06:00:00+00', timestamptz '2023-03-11 18:00:00+00', 'day', 'coffeeSketch', 'V2'),
  ('arch-exhibition', 'published', 'Arch Exhibition', 'معرض أرتش', 'MAZJ as knowledge partner', 'مزج شريكاً معرفياً', timestamptz '2023-03-15 06:00:00+00', timestamptz '2023-03-15 18:00:00+00', 'month', null, null),
  ('origami-and-architecture', 'published', 'Origami and Architecture', 'الأوريجامي والعمارة', 'building your own structures', 'لتصميم هياكلك الخاصة', timestamptz '2023-02-17 06:00:00+00', timestamptz '2023-02-18 18:00:00+00', 'day', null, null),
  ('coffee-sketch-v1', 'published', 'Coffee & Sketch', 'قهوة وسكتش', 'Asma Habib', 'أسماء حبيب', timestamptz '2023-02-15 06:00:00+00', timestamptz '2023-02-15 18:00:00+00', 'day', 'coffeeSketch', 'V1'),
  ('evening-dress-design', 'published', 'Evening dress design', 'تصميم فستان السهرة', 'a fashion workshop', 'ورشة أزياء', timestamptz '2023-02-15 06:00:00+00', timestamptz '2023-02-15 18:00:00+00', 'month', null, null),
  ('loqma-w-fayda-v1', 'published', 'Loqma w Fayda', 'لقمة وفايدة', 'the series opens', 'انطلاق السلسلة', timestamptz '2023-02-15 06:00:00+00', timestamptz '2023-02-15 18:00:00+00', 'month', 'loqmaFayda', 'V1'),
  ('al-asala-university', 'published', 'Al-Asala University', 'جامعة الأصالة', 'MAZJ as knowledge partner, College of Architecture & Design', 'مزج شريكاً معرفياً، كلية العمارة والتصميم', timestamptz '2022-11-15 06:00:00+00', timestamptz '2022-11-15 18:00:00+00', 'month', null, null)
on conflict (slug) do nothing;
